/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-01-28

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include "stm32f4xx.h"
#include "main.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */

int main(void) {
	int i = 0;
	t_baudrate baudrate = 115200;
	/* Initialisation de la liaison série*/
	serial_init(baudrate);
	/* Initialisation VT100 */
	vt100_clear_screen();


	t_ship player = { PLAYER_POSITION_X, PLAYER_POSITION_Y, PLAYER_SHIP,
	PLAYER_LIFE };
	t_ship enemy =
			{ ENEMY_POSITION_X, ENEMY_POSITION_Y, ENEMY_SHIP, ENEMY_LIFE };

	/* Initialisation du terrain de jeu */
	t_character playground[VT100_SCREEN_WIDTH][VT100_SCREEN_HEIGHT] = { 0 }; /* 80 x 24 */

	/* Initialisation des ennemies */
	t_ship enemies[165] = { 0 };
	initEnemy(enemies, enemy, 33, 5);
	initPlayground(playground, enemies);

	/* Test d'affichage */
	playground[player.pos_x][player.pos_y] = player.ship;
	vt100_move(player.pos_x, player.pos_y);
	serial_putchar(playground[player.pos_x][player.pos_y]);

	/* TODO - Add your application code here */

	/* Infinite loop */
	while (1) {
		i++;
	}
}

void initPlayground(uint8_t tab_playground[80][24], t_ship *tab_enemies) {
	/*uint16_t i = 0;
	uint8_t *p_playground = 0;

	t_character ship = 0;
	uint16_t position = 0;


	p_playground = (uint8_t*)tab_playground;*/

	/*for(i=0; i<=1919; i++){
		*(p_playground)= 'A';
		p_playground++;
	}*/

	/* Remplissage du terrain de jeu avec les vaisseaux */
	uint8_t j = 0;
	for(j=0; j<=164; j++){
		tab_playground[tab_enemies[j].pos_x][tab_enemies[j].pos_y] = tab_enemies[j].ship;
		vt100_move(tab_enemies[j].pos_x,tab_enemies[j].pos_y);
		serial_putchar(tab_enemies[j].ship);
	}

}

/* Fonction d'initialisation des vaisseaux ennemies */
void initEnemy(t_ship *tab_enemies, t_ship enemy, uint8_t enemy_in_line,

		uint8_t nbr_of_line) {
	uint8_t count_line;
	uint8_t count_enemies;
	uint8_t total_enemies;

	total_enemies = 0;

	for (count_line = 0; count_line <= nbr_of_line - 1; count_line++) {
		enemy.pos_x = ENEMY_POSITION_X;

		for (count_enemies = 0; count_enemies <= enemy_in_line - 1;
				count_enemies++) {
			tab_enemies[total_enemies] = enemy;
			enemy.pos_x += 2;
			total_enemies += 1;
		}
		enemy.pos_y += 2;

	}
	/*for (y = 0; y <= 23; y++) {
		for (x = 0; x <= 79; x++) {
			tab_playground[y][x] = 'A';
		}
	}*/
}

void initcreen(uint8_t tab_playground[80][24]){
	uint16_t count_case;



}
