/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-01-28

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include "stm32f4xx.h"
#include "main.h"
#include "enemy.h"
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */

int main(void) {
	/* INITIALISATION */
	/* Initialisation des variables */
	int i = 0;
	t_character user_input = 0;

	/* Variables : déplacement des vaisseaux ennemies */

	uint8_t dir = RIGHT;

	/* Variables : temps */
	uint32_t time_player = 100000;
	uint32_t time = 100000;

	/* Variables : texte */
	t_character txt_score[] = "SCORE : ";
	t_character txt_life[] = "NOMBRE DE VIES : ";

	/* Variables : missiles */
	uint8_t tire_player = FALSE;

	/* Initialisation de la liaison série*/
	serial_init(BAUDRATE);

	/* Initialisation VT100 */
	vt100_clear_screen();

	/* Déclaration du joueur / des ennemies / du terrain de jeu / missile */

	t_player player = { PLAYER_POSITION_X, PLAYER_POSITION_Y, PLAYER_SHIP,
	PLAYER_SCORE,
	PLAYER_LIFE };

	t_character playgroundPlayer[VT100_SCREEN_WIDTH] = { 0 };
	playgroundPlayer[player.pos_x] = player.ship;

	t_ship enemy = { ENEMY_POSITION_X, ENEMY_POSITION_Y, 0, ENEMY_SHIP,
	ENEMY_LIFE };

	t_rocket player_rocket = { 0, 0, 0, 0, '|' };

	/* Initialisation du terrain de jeu */
	t_character playground[VT100_SCREEN_WIDTH][VT100_SCREEN_HEIGHT] = { 0 }; /* 80 x 24 */

	/* Initialisation des ennemies */
	t_ship enemies[ENEMIES] = { 0 };
	initEnemy(enemies, enemy, ENEMIES_PER_LINE, ENEMIES_PER_COL);
	initPlayground(playground, enemies);

	/* Initialisation du joueur */
	playground[player.pos_x][player.pos_y] = player.ship;
	vt100_move(player.pos_x, player.pos_y);
	serial_putchar(playground[player.pos_x][player.pos_y]);

	/* TODO - Add your application code here */

	/* Infinite loop */
	while (1) {
		/* Initialisation du jeu */

		while ((enemies[ENEMIES - 1].new_pos_y != PLAYER_POSITION_Y - 1)
				|| (player.life == 0)) {
			/* Affichae du :
			 * - score
			 * - nombre de vies du joueur
			 */

			vt100_move(1, 1);
			serial_puts(txt_score);
			serial_putchar(player.score);
			vt100_move(1, 24);
			serial_puts(txt_life);
			serial_putchar(player.life);

			/* Déplacement du joueur */
			for (i = 0; i <= time_player; i++) {

				user_input = serial_get_last_char();

				if (((user_input == 'd') || (user_input == 'D'))
						&& (player.pos_x != VT100_SCREEN_WIDTH)) {

					/* Déplacement joueur */
					player.pos_x = moveShipLR(playgroundPlayer, RIGHT,
							player.pos_x);
					vt100_move(player.pos_x, player.pos_y);
					vt100_clear_line();
					serial_putchar(playgroundPlayer[player.pos_x]);

				} else if (((user_input == 'q') || (user_input == 'Q'))
						&& (player.pos_x != 0)) {

					/* Déplacement joueur */
					player.pos_x = moveShipLR(playgroundPlayer, LEFT,
							player.pos_x);
					vt100_move(player.pos_x, player.pos_y);
					vt100_clear_line();
					serial_putchar(playgroundPlayer[player.pos_x]);
					/* Déplacement des ennemies */

					/* Déplacement des missiles (joueur & ennemies) */

				} else if (((user_input == 'z') || (user_input == 'Z'))
						&& (tire_player == FALSE)) {

					/* Nothing to do */
					/* Déplacement des missiles (joueur & ennemies) */
					player_rocket.pos_x = player.pos_x;
					player_rocket.pos_y = player.pos_y - 1;
					tire_player = TRUE;
				}

			}

			/* Déplacement des missiles */
			moveRocket(&player_rocket, &tire_player); // rocket joueur

			isEnemyShoot(enemies, &player_rocket, &tire_player);

			/* Déplacement des ennemies */
			displayEnemies(enemies, &dir);
			displayEnemiesOnPlayground(playground, enemies);
			delay(time);

			isEnemyShoot(enemies, &player_rocket, &tire_player);
		}
		/* GAME OVER */
	}

}

void initPlayground(uint8_t tab_playground[80][24], t_ship *tab_enemies) {
	uint8_t j = 0;
	for (j = 0; j <= ENEMIES - 1; j++) {
		tab_playground[tab_enemies[j].pos_x][tab_enemies[j].pos_y] =
				tab_enemies[j].ship;
		vt100_move(tab_enemies[j].pos_x, tab_enemies[j].pos_y);
		serial_putchar(tab_enemies[j].ship);
	}

}

/* Fonction d'initialisation des vaisseaux ennemies */
void initEnemy(t_ship *tab_enemies, t_ship enemy, uint8_t enemy_in_line,
		uint8_t nbr_of_line) {
	uint8_t count_line;
	uint8_t count_enemies;
	uint8_t total_enemies;

	total_enemies = 0;

	for (count_line = 0; count_line <= nbr_of_line - 1; count_line++) {
		enemy.pos_x = ENEMY_POSITION_X;

		for (count_enemies = 0; count_enemies <= enemy_in_line - 1;
				count_enemies++) {
			enemy.new_pos_y = enemy.pos_y;
			tab_enemies[total_enemies] = enemy;
			enemy.pos_x += 2;
			total_enemies += 1;
		}
		enemy.pos_y += 2;

	}
}

void displayEnemiesOnPlayground(uint8_t tab_playground[80][24],
		t_ship *tab_enemies) {
	/* Déplacement en x de l'ennemi n */
	/* Variables */

	/* Quand on arrive au bout de la ligne, déplacement en y de l'ennemi n */
	/* Remplissage du terrain de jeu avec les vaisseaux */
	uint8_t j = 0;
	uint8_t ligne = 0;
	for (j = 0; j <= ENEMIES - 1; j++) {
		/* Déplacement du vaisseau */
		tab_playground[tab_enemies[j].pos_x][tab_enemies[j].pos_y] =
				tab_enemies[j].ship;

		/* Effacement de la ligne */
		if ((ligne != tab_enemies[j].pos_y)
				&& ((tab_enemies[j].pos_y) == (tab_enemies[j].new_pos_y))) {

			/* On passe au vaisseau suivant */
			vt100_move(tab_enemies[j].pos_x, tab_enemies[j].pos_y);
			vt100_clear_line();

			ligne = tab_enemies[j].pos_y;

		} else if ((ligne != tab_enemies[j].pos_y)
				&& ((tab_enemies[j].pos_y) != (tab_enemies[j].new_pos_y))) {
			/* On efface la ligne précédente avant de passer à la suivante */
			vt100_move(tab_enemies[j].pos_x, tab_enemies[j].pos_y);
			vt100_clear_line();
			/* On passe à la ligne suivante */
			vt100_move(tab_enemies[j].pos_x, tab_enemies[j].new_pos_y);

			/* On stock la nouvelle position */
			tab_enemies[j].pos_y = tab_enemies[j].new_pos_y;
			ligne = tab_enemies[j].pos_y;
		}

		vt100_move(tab_enemies[j].pos_x, tab_enemies[j].pos_y);
		serial_putchar(tab_enemies[j].ship);
		ligne = tab_enemies[j].pos_y;
	}
}

uint8_t moveShipLR(t_character *tab_ship, uint8_t way, t_pos old_pos) {

	if (way == LEFT) {
		tab_ship[old_pos - 1] = tab_ship[old_pos];
		tab_ship[old_pos] = '\0';
		old_pos -= 1;
	} else if (way == RIGHT) {
		tab_ship[old_pos + 1] = tab_ship[old_pos];
		tab_ship[old_pos] = '\0';
		old_pos += 1;
	}
	//vt100_clear_line();
	return old_pos;
}

void moveRocket(t_rocket *rocket, uint8_t *shoot) {
	if (*shoot == TRUE) {
		/* Suppression de la rocket précédente */
		vt100_move(rocket->old_pos_x, rocket->old_pos_y);
		serial_putchar(0x20);

		/* Affichage de la rocket */
		vt100_move(rocket->pos_x, rocket->pos_y);
		serial_putchar(rocket->rocket);

		/* On sauvgarde l'ancienne position de la rocket */
		rocket->old_pos_x = rocket->pos_x;
		rocket->old_pos_y = rocket->pos_y;

		rocket->pos_y -= 1;

		if (rocket->pos_y == 0) {
			vt100_move(rocket->old_pos_x, rocket->old_pos_y);
			serial_putchar(0x20);
			*shoot = FALSE;

		} else {
			*shoot = TRUE;
		}
	} else {
		*shoot = FALSE;
	}
}

void isEnemyShoot(t_ship *tab_enemies, t_rocket *rocket, uint8_t *shoot) {
	uint8_t count_enemies = 0;
	if (*shoot == TRUE) {
		for (count_enemies = 0; count_enemies <= ENEMIES - 1; count_enemies++) {
			/* Si l'ennemi est en vie */
			if (tab_enemies[count_enemies].life == 1) {
				/* Si la position de la rocket et de l'ennemi sont égales, alors on tue l'ennemi */
				if ((tab_enemies[count_enemies].pos_x == rocket->pos_x)
						&& (tab_enemies[count_enemies].pos_y == rocket->pos_y)) {
					/* On fait disparaitre l'ennemi */
					tab_enemies[count_enemies].life = 0;
					tab_enemies[count_enemies].ship = 0x20;
					/* Ajouter un délai */
					vt100_move(rocket->old_pos_x, rocket->old_pos_y);
					serial_putchar(0x20);

					*shoot = FALSE;

				}

			} else {
				/* Sinon on passe à l'ennemi suivant */
				count_enemies += 1;
			}
		}
	}

}

void delay(uint32_t time) {
	uint32_t i;
	for (i = 0; i <= time; i++)
		;
}

